image: node:latest


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

before_script:
    - npm install

test:
    image: trion/ng-cli-karma
    stage: test
    environment: test
    script:
        - setsid './gitlab-test.sh'
        - npm run test
        - npm run e2e
    coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
    artifacts:
        paths:
            - coverage/

build:
    stage: build
    environment: build
    script:
        - npm run build:prod
    cache:
        policy: push
        paths:
            - node_modules/
    only: 
        - master
    artifacts:
        paths:
            - dist/
            - backend/
            - server.js
            - package.json
            - README.md
            - LICENSE

