language: node_js
node_js:
  - "stable"

branches:
  only:
  - master
  - dev

before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch=false --browsers=ChromeHeadless
  - ng build --prod