language: node_js
node_js:
  - "stable"

branches:
  only:
  - master
  - dev

before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch=false --browsers=ChromeHeadless
  - npm run coveralls
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Typescript -r ./coverage/grow-local/lcov.info
  - ng build --prod

notifications:
  webhooks: https://coveralls.io/webhook